### ISSUE TITLE
if this point doesn't have a valid alt

### ISSUE THREAD

**Issue by xieyongchao2** [alexcojocaru/geo-data-exchange#1]
Hello, [I see this line of segmented code.](https://github.com/alexcojocaru/geo-data-exchange/blob/cb103a1c2e9b0adbabf4851d34474f3a76e9f277/src/index.js#L184) What is [“if this point doesn't have a valid alt.”](https://github.com/alexcojocaru/geo-data-exchange/blob/cb103a1c2e9b0adbabf4851d34474f3a76e9f277/src/index.js#L184) How is this data generated?

**Comment by alexcojocaru** [comment]
I am not quite following your ask.

You asked why the `alt` coordinate could be missing. That's because points on a GPX track are still considered valid even without altitude.

You asked how the data is generated. I don't know, that's up to the user of this library to generate the data and pass it to the main `buildGeojsonFeatures` function. Accounting for some invalid or incomplete input data is called fault tolerance.
